### PR TITLE
Update deprecated View.propTypes to ViewPropTypes

### PR DESCRIPTION
**Pull request by cooperka**
See React Native release notes for more info: https://github.com/facebook/react-native/releases/tag/v0.44.3. (This is a breaking change.)

### CODE REVIEW

**Comment by jineshshah36** [comment]
Released as 1.2.1, thanks! I haven't been doing much react-native work lately so this repo has been getting a little stale.

**Comment by cooperka** [comment]
Thanks @jineshshah36! Note that because this is a breaking change, you might want to bump your major version number. It requires React Native `>= 0.44`.

**Comment by cooperka** [comment]
To be clear, you may want to release v1.2.2 with this change **reverted**, followed by v2.0.0 (or at the very least v1.3.0) with this change.

Anyone depending on your package using a tilde or carat notation (e.g. `~1.2.0`) will receive this update automatically and their app will break if they don't happen to have a high enough React Native version.

**Comment by jineshshah36** [comment]
Thanks for the update, I just made those changes

**Comment by cooperka** [comment]
Thanks again @jineshshah36, I appreciate it 😄

**Comment by jineshshah36** [comment]
No, thank you for contributing! Also, I used to go to Michigan. I remember Cribspot!

**Comment by cooperka** [comment]
Whoa, that's crazy haha. What year were you?

**Comment by jineshshah36** [comment]
Graduated 2015, I was in the School of Information

**Comment by cooperka** [comment]
Small world 😉 I was 2014 in CSE. Thanks for the lib, you're helping to make Cribspot better for everyone!

**Pull request merged**
